### ISSUE TITLE
Tablas de clase listing

### ISSUE THREAD

**Issue by adriana-rv** [imatem/imtheme.blue#32]
Después del cambio del tema, las tablas con class="listing" quedaron horribles para leer, seguro el coordinador de becas lo indicará.

**Comment by adriana-rv** [comment]
No son exactamente las tablas de clase listing es porque se usa un div(id "applications") con clase "active" pero ese es necesario porque lo usa bootstrap, pero si lo quitas se corroje la vista.  Usa el .active del tema imblue-compiled.css 297 background 717171.

**Comment by gil-cano** [comment]
ver servicios/becarios/registros/allapplications
