### ISSUE TITLE
Texto pie de página

### ISSUE THREAD

**Issue by adriana-rv** [imatem/imtheme.blue#35]
En el pie de página se encuentra mal escrita "Área de la Investigación Cientifica" debe ser reemplazada por "Área de la Investigación Científica"

**Comment by adriana-rv** [comment]
También le falta un acento a México en la dirección del IM

**Comment by adriana-rv** [comment]
Todavía no se ven los cambios

**Comment by gil-cano** [comment]
Si, cuando la corrección se sube a github se cierra el issue. Cuando se aga el release o se actualice el maste en info se aplican todos los cambios.

**Comment by adriana-rv** [comment]
ok, espero para ver los cambios ;-)
